---
- name: Demo policies multiple conditions all
  hosts: localhost
  vars:
    vars_i: 10
  policies:
    - name: multiple conditions
      target: rest
      condition: 
        all:
          - action.first != vars_i or action.first != 0
          - context.second != vars_i or context.second != 0 and context.third != 0
      exception: principal == resource.owner
      actions:
        - permit: 
            principal: User::"admin"
            action: Action::"allow"
            resource:
              in: Dir::"hello"
        - forbid: 
            action: 
              is: Test
              in: Action::"allow"
            resource: 
              is: File
      tags:
        - compliance
        